# Generated by Django 5.2.6 on 2026-08-18 05:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='الاسم')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'merchant'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول')),
            ],
            options={
                'verbose_name': 'تاجر',
                'verbose_name_plural': 'التجار',
                'ordering': ['name'],
                'permissions': [('manage_merchants', 'إدارة التجار وطرقهم ومحافظهم')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('code', models.SlugField(help_text='معرّف ثابت يُستخدم في الشيفرة والتقارير، ولا يُغيَّر بعد الإنشاء.', unique=True, verbose_name='الرمز')),
                ('caption_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('caption_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='الأيقونة')),
                ('supports_deposit', models.BooleanField(default=True, verbose_name='يدعم الإيداع')),
                ('supports_withdrawal', models.BooleanField(default=True, verbose_name='يدعم السحب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='الأصغر يظهر أولًا.', verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['sort_order', 'caption_ar'],
                'constraints': [models.CheckConstraint(condition=models.Q(('supports_deposit', True), ('supports_withdrawal', True), _connector='OR'), name='paymentmethod_supports_at_least_one_direction')],
            },
        ),
        migrations.CreateModel(
            name='MerchantMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='merchants.merchant', verbose_name='التاجر')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_methods', to='merchants.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طريقة دفع لتاجر',
                'verbose_name_plural': 'طرق الدفع للتجار',
                'ordering': ['merchant__name', 'payment_method__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('number', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{4,64}$', message='رقم المحفظة يقبل الأرقام والمسافات وعلامتي + و - فقط.')], verbose_name='رقم المحفظة')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='التسمية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('daily_cap', models.DecimalField(blank=True, decimal_places=2, help_text='فارغ يعني بلا سقف.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السقف اليومي')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='أُلغي تفعيلها في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallets', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('merchant_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='merchants.merchantmethod', verbose_name='طريقة الدفع للتاجر')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchantmethod',
            constraint=models.UniqueConstraint(fields=('merchant', 'payment_method'), name='unique_merchant_payment_method'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('merchant_method',), name='one_active_wallet_per_merchant_method'),
        ),
    ]
