# Generated by Django 5.2.6 on 2026-08-20 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='daily_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إجمالي ما تستقبله هذه المحفظة في اليوم بالدينار العراقي، شاملًا العمولة. فارغ يعني بلا سقف.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السقف اليومي (دينار عراقي)'),
        ),
    ]
