# Generated by Django 5.2.6 on 2026-08-24 20:16

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_wallet_daily_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_wallet_number',
            field=models.BooleanField(default=True, help_text='أوقفه للطرق التي تُدفع بمسح رمز QR أو بصورة تعليمات بدل كتابة رقم. عندها يمكن أن تكون المحفظة صورة بلا رقم.', verbose_name='يُدفع برقم محفظة'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, help_text='تظهر للعميل مكان رقم المحفظة. صورة فقط، بحدود الحجم المعتادة.', upload_to='wallets/%Y/%m/', validators=[apps.core.validators.FileSizeValidator(), apps.core.validators.UploadContentValidator()], verbose_name='صورة المحفظة أو رمز QR'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.CharField(blank=True, help_text='يُترك فارغًا فقط للطرق التي تُدفع بصورة أو رمز QR.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{4,64}$', message='رقم المحفظة يقبل الأرقام والمسافات وعلامتي + و - فقط.')], verbose_name='رقم المحفظة'),
        ),
    ]
