"""Rename ``Wallet.image`` to ``Wallet.qr_image``.

Hand-written rather than autogenerated. ``makemigrations`` sees a field
disappear and another appear and offers to drop one and create the other, which
would delete every QR Finance has uploaded. A rename keeps the column and its
contents; only the name and the wording around it change.

The wording is the point of the change. ``image`` sat one letter away from
``PaymentMethod.icon``, with nothing in either name to say that one is a brand
mark rendered beside a caption and the other is a code a client points a camera
at.
"""

import django.core.validators
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_paymentmethod_requires_wallet_number_wallet_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="image",
            new_name="qr_image",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="qr_image",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "الرمز الذي يمسحه العميل بتطبيق الدفع. يظهر كبيرًا في شاشة تفاصيل "
                    "الطلب تحت عنوان صريح، لا كشعار. ارفع صورة الرمز نفسه لا شعار "
                    "الطريقة — شعار الطريقة يُرفع في «طرق الدفع»."
                ),
                upload_to="wallets/%Y/%m/",
                validators=[
                    apps.core.validators.validate_upload_size,
                    apps.core.validators.validate_upload_content,
                ],
                verbose_name="رمز QR للدفع",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="يُترك فارغًا فقط للطرق التي تُدفع برمز QR.",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[0-9+\-\s]{4,64}$",
                        message="رقم المحفظة يقبل الأرقام والمسافات وعلامتي + و - فقط.",
                    )
                ],
                verbose_name="رقم المحفظة",
            ),
        ),
    ]
