# Generated by Django 5.2.6 on 2026-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_wallet_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, help_text='علامة صغيرة تظهر بجانب اسم الطريقة في قائمة العميل، للتعريف فقط. ليست رمزًا يُمسح — رمز QR يُرفع على المحفظة نفسها في صفحة التاجر.', null=True, upload_to='payment_methods/', verbose_name='أيقونة الطريقة'),
        ),
    ]
