# Generated by Django 5.2.6 on 2026-08-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_payment_method_icon_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['name'], 'permissions': [('manage_merchants', 'إدارة التجار وطرقهم ومحافظهم'), ('archive_merchants', 'أرشفة التجار وحذف المحافظ')], 'verbose_name': 'تاجر', 'verbose_name_plural': 'التجار'},
        ),
        migrations.AddField(
            model_name='merchant',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='أُرشف في'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_merchants', to=settings.AUTH_USER_MODEL, verbose_name='أرشفه'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='أُرشفت في'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_wallets', to=settings.AUTH_USER_MODEL, verbose_name='أرشفها'),
        ),
    ]
