# Generated by Django 5.2.6 on 2026-09-03 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_merchant_and_wallet_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='b2core_id',
            field=models.CharField(blank=True, help_text='معرّف التاجر في B2CORE، للمطابقة اليدوية عند التسوية. اتركه فارغًا إن لم يكن له حساب هناك. لا يُتحقق منه آليًا.', max_length=128, null=True, unique=True, verbose_name='معرّف B2CORE'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.CheckConstraint(condition=models.Q(('b2core_id__isnull', True), models.Q(('b2core_id', ''), _negated=True), _connector='OR'), name='merchant_b2core_id_null_not_blank'),
        ),
    ]
