# Generated by Django 5.2.6 on 2026-09-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_merchant_b2core_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='b2core_id',
            field=models.CharField(blank=True, help_text='معرّف التاجر في B2CORE. هو ما يُفتح به دخول التاجر إلى لوحته من داخل B2CORE: يُقارَن بالمُعرّف الموقّع في الرمز، فإن تطابقا فُتحت الجلسة. خطأ في كتابته يمنع التاجر من الدخول. اتركه فارغًا إن لم يكن له حساب هناك.', max_length=128, null=True, unique=True, verbose_name='معرّف B2CORE'),
        ),
    ]
