# Generated by Django 5.2.6 on 2026-08-18 05:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب')], db_index=True, max_length=20, verbose_name='النوع')),
                ('iqd_per_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='دينار لكل دولار')),
                ('commission_iqd_per_100usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='العمولة بالدينار لكل 100 دولار')),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='سارٍ من')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates_set', to=settings.AUTH_USER_MODEL, verbose_name='حدّده')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'ordering': ['-effective_from', '-id'],
                'abstract': False,
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['rate_type', '-effective_from'], name='rate_type_effective_idx')],
            },
        ),
    ]
