# Generated by Django 5.2.6 on 2026-08-18 05:21

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('b2core_id', models.CharField(db_index=True, help_text='مطالبة sub الموثّقة من رمز B2CORE.', max_length=128, unique=True, verbose_name='معرّف B2CORE')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('account_number', models.CharField(blank=True, help_text='للعرض لدى المالية فقط، ولا يُقبل أبدًا من إدخال العميل.', max_length=64, verbose_name='رقم الحساب')),
                ('preferred_language', models.CharField(default='ar', max_length=8, verbose_name='اللغة المفضلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
                'permissions': [('view_client_pii', 'الاطلاع على البيانات الشخصية للعميل')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('finance_admin', 'مدير مالي'), ('finance_staff', 'موظف مالي'), ('merchant', 'تاجر')], db_index=True, help_text='يحدد مجموعة الصلاحيات الممنوحة تلقائيًا.', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, help_text='ألغِ التفعيل بدل الحذف حتى تبقى سجلات التدقيق مرتبطة.', verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=True, help_text='كل الحسابات الداخلية تستخدم لوحة الإدارة.', verbose_name='يدخل لوحة الإدارة')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP للدخول')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم داخلي',
                'verbose_name_plural': 'المستخدمون الداخليون',
                'ordering': ['full_name', 'email'],
                'permissions': [('manage_internal_users', 'إدارة المستخدمين الداخليين وأدوارهم'), ('manage_permissions', 'منح وسحب الصلاحيات'), ('reset_user_two_factor', 'إعادة تعيين المصادقة الثنائية لمستخدم'), ('view_client_identity', 'الاطلاع على هوية العميل'), ('view_audit_log', 'عرض سجل التدقيق')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
