# Generated by Django 5.2.6 on 2026-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='denied_permissions',
            field=models.ManyToManyField(blank=True, help_text='تُطرح من صلاحيات الدور، حتى لو منحتها المجموعة.', related_name='denied_for', to='auth.permission', verbose_name='صلاحيات ممنوعة'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='يُفرض على المستخدم اختيار كلمة مرور جديدة قبل استخدام النظام. يُضبط تلقائيًا عند إنشاء الحساب أو إعادة تعيين كلمة المرور.', verbose_name='يجب تغيير كلمة المرور'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر إعادة تعيين للمصادقة الثنائية'),
        ),
    ]
