# Generated by Django 5.2.6 on 2026-08-18 05:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('open_time', models.TimeField(default=datetime.time(9, 0), verbose_name='وقت الفتح')),
                ('close_time', models.TimeField(default=datetime.time(21, 0), verbose_name='وقت الإغلاق')),
                ('timezone', models.CharField(default='Asia/Baghdad', max_length=64, verbose_name='المنطقة الزمنية')),
                ('is_open_override', models.BooleanField(blank=True, default=None, help_text='فارغ: اتبع مواعيد العمل. نعم: افتح دائمًا. لا: أغلق دائمًا.', null=True, verbose_name='تجاوز حالة الفتح')),
                ('closed_message_ar', models.TextField(default='النظام مغلق حاليًا. يرجى المحاولة خلال ساعات العمل.', verbose_name='رسالة الإغلاق')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='لقطة نصية للمنفّذ وقت الحدث، تبقى بعد حذف حسابه.', max_length=150, verbose_name='وصف المنفّذ')),
                ('action', models.CharField(choices=[('status_change', 'تغيير الحالة'), ('wallet_change', 'تغيير محفظة'), ('rate_change', 'تغيير سعر الصرف'), ('permission_change', 'تغيير الصلاحيات'), ('user_change', 'تغيير مستخدم'), ('merchant_change', 'تغيير تاجر'), ('settings_change', 'تغيير إعدادات النظام'), ('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('two_factor_change', 'تغيير المصادقة الثنائية')], db_index=True, max_length=40, verbose_name='الإجراء')),
                ('target_type', models.CharField(db_index=True, max_length=100, verbose_name='نوع الهدف')),
                ('target_id', models.CharField(db_index=True, max_length=64, verbose_name='معرّف الهدف')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='بعد')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الحدث')),
                ('actor', models.ForeignKey(blank=True, help_text='فارغ إذا كان المنفّذ النظام أو عميلاً.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_time_idx')],
            },
        ),
    ]
