# Generated by Django 5.2.6 on 2026-08-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_append_only_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('status_change', 'تغيير الحالة'), ('amount_change', 'تعديل المبلغ'), ('wallet_change', 'تغيير محفظة'), ('rate_change', 'تغيير سعر الصرف'), ('permission_change', 'تغيير الصلاحيات'), ('user_change', 'تغيير مستخدم'), ('merchant_change', 'تغيير تاجر'), ('settings_change', 'تغيير إعدادات النظام'), ('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('two_factor_change', 'تغيير المصادقة الثنائية')], db_index=True, max_length=40, verbose_name='الإجراء'),
        ),
    ]
