# Generated by Django 5.2.6 on 2026-08-18 05:21

import apps.core.validators
import apps.transactions.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('file', models.FileField(upload_to=apps.transactions.models.attachment_upload_path, validators=[apps.core.validators.FileSizeValidator(), apps.core.validators.UploadContentValidator()], verbose_name='الملف')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المحتوى')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='الحجم')),
                ('uploaded_by_role', models.CharField(choices=[('client', 'العميل'), ('finance_admin', 'مدير مالي'), ('finance_staff', 'موظف مالي'), ('merchant', 'تاجر'), ('system', 'النظام')], max_length=20, verbose_name='رفعه')),
                ('uploaded_by_id', models.PositiveBigIntegerField(blank=True, help_text='مفتاح الحساب الداخلي أو العميل حسب الدور.', null=True, verbose_name='معرّف الرافع')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الرفع')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('public_ref', models.CharField(db_index=True, editable=False, help_text='المعرّف الوحيد الذي يراه التاجر.', max_length=16, unique=True, verbose_name='المرجع')),
                ('type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب')], db_index=True, max_length=20, verbose_name='النوع')),
                ('wallet_number_snapshot', models.CharField(blank=True, max_length=64, verbose_name='رقم المحفظة وقت التقديم')),
                ('destination_account', models.CharField(blank=True, help_text='للسحب فقط: بطاقة العميل أو رقم محفظته.', max_length=64, verbose_name='حساب الوجهة')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ بالدولار')),
                ('amount_iqd', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ بالدينار')),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المطبَّق')),
                ('commission_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='العمولة المطبَّقة')),
                ('status', models.CharField(choices=[('submitted', 'مُقدَّم'), ('under_review', 'قيد المراجعة'), ('assigned', 'مُسند إلى تاجر'), ('merchant_confirmed', 'أكّد التاجر الاستلام'), ('merchant_paid', 'دفع التاجر'), ('credited', 'قُيِّد في B2CORE'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], db_index=True, default='submitted', max_length=25, verbose_name='الحالة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التقديم')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإسناد')),
                ('merchant_actioned_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تنفيذ التاجر')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.client', verbose_name='العميل')),
                ('merchant_assigned', models.ForeignKey(blank=True, help_text='قد يختلف عن التاجر الذي اختاره العميل.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_assigned', to='merchants.merchant', verbose_name='التاجر المُسند من المالية')),
                ('merchant_selected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_selected', to='merchants.merchant', verbose_name='التاجر المختار من العميل')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='merchants.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-submitted_at', '-id'],
                'permissions': [('route_request', 'إسناد الطلب إلى تاجر'), ('approve_request', 'اعتماد الطلب'), ('credit_request', 'تسجيل الإيداع في B2CORE'), ('close_request', 'إغلاق الطلب'), ('confirm_request', 'تأكيد تنفيذ الطلب'), ('reject_request', 'رفض الطلب'), ('view_all_requests', 'عرض جميع الطلبات وليس المُسندة فقط')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('sender_role', models.CharField(choices=[('client', 'العميل'), ('finance_admin', 'مدير مالي'), ('finance_staff', 'موظف مالي'), ('merchant', 'تاجر'), ('system', 'النظام')], db_index=True, max_length=20, verbose_name='دور المُرسل')),
                ('sender_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='معرّف المُرسل')),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                ('is_internal_note', models.BooleanField(default=False, help_text='تظهر للمالية فقط، ولا تُرسل للعميل أو التاجر.', verbose_name='ملاحظة داخلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الإرسال')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='transactions.attachment', verbose_name='المرفق')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transactions.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.request', verbose_name='الطلب'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', '-submitted_at'], name='request_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['merchant_assigned', 'status'], name='request_merchant_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['client', '-submitted_at'], name='request_client_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['request', 'created_at'], name='message_request_time_idx'),
        ),
    ]
