# Generated by Django 5.2.6 on 2026-08-22 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='وقت الاطلاع')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='transactions.request', verbose_name='الطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_reads', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اطلاع على طلب',
                'verbose_name_plural': 'الاطلاعات على الطلبات',
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'request'], name='requestread_user_req_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'request'), name='requestread_unique_user_request')],
            },
        ),
    ]
