# Generated by Django 5.2.6 on 2026-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-submitted_at', '-id'], 'permissions': [('route_request', 'إسناد الطلب إلى تاجر'), ('approve_request', 'اعتماد الطلب'), ('credit_request', 'تسجيل الإيداع في B2CORE'), ('close_request', 'إغلاق الطلب'), ('confirm_request', 'تأكيد تنفيذ الطلب'), ('reject_request', 'رفض الطلب'), ('view_all_requests', 'عرض جميع الطلبات وليس المُسندة فقط'), ('return_request', 'إعادة الطلب إلى المالية'), ('cancel_request', 'إلغاء الطلب'), ('export_reports', 'تصدير التقارير إلى ملف')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('submitted', 'مُقدَّم'), ('under_review', 'قيد المراجعة'), ('assigned', 'مُسند إلى تاجر'), ('pending', 'مُعلَّق بانتظار المالية'), ('merchant_confirmed', 'أكّد التاجر الاستلام'), ('merchant_paid', 'دفع التاجر'), ('credited', 'قُيِّد في B2CORE'), ('closed', 'مغلق'), ('rejected', 'مرفوض'), ('cancelled', 'مُلغى')], db_index=True, default='submitted', max_length=25, verbose_name='الحالة'),
        ),
    ]
