# Generated by Django 5.2.6 on 2026-08-24 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_submitted_amounts(apps, schema_editor):
    """Every request that already exists was submitted at the amount it holds.

    Left null they would read as "never corrected, and we do not know what was
    asked for", which is wrong on both halves: nothing has been corrected yet,
    and what was asked for is exactly what is stored.
    """
    Request = apps.get_model("transactions", "Request")
    Request.objects.filter(submitted_amount_usd__isnull=True).update(
        submitted_amount_usd=models.F("amount_usd"),
        submitted_amount_iqd=models.F("amount_iqd"),
    )


def unbackfill(apps, schema_editor):
    """Nothing to undo: the columns go with the migration."""


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_request_options_alter_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر معالجة'),
        ),
        migrations.AddField(
            model_name='request',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عالجه'),
        ),
        migrations.AddField(
            model_name='request',
            name='submitted_amount_iqd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='المبلغ المطلوب أصلًا بالدينار'),
        ),
        migrations.AddField(
            model_name='request',
            name='submitted_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المطلوب أصلًا بالدولار'),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, help_text='اتركه فارغًا ليُولَّد من النوع والمبلغ ويتبعهما عند التعديل.', max_length=120, verbose_name='عنوان الطلب'),
        ),
        migrations.RunPython(backfill_submitted_amounts, unbackfill),
    ]
