# Generated by Django 5.2.6 on 2026-08-24 22:36

from decimal import Decimal

from django.db import migrations, models


def backfill_commission_rate(apps, schema_editor):
    """Recover the per-100 rate from the pair every existing request holds.

    ``commission_applied`` is that rate's answer for ``amount_usd``, so the
    rate is the answer divided back out. Exact for every row the system wrote,
    because both halves came from the same arithmetic; a request whose amount
    is somehow zero is skipped rather than divided by it.
    """
    Request = apps.get_model("transactions", "Request")
    for request_obj in Request.objects.filter(
        commission_rate_applied__isnull=True
    ).exclude(amount_usd=0).iterator():
        request_obj.commission_rate_applied = (
            request_obj.commission_applied * 100 / request_obj.amount_usd
        ).quantize(Decimal("0.01"))
        request_obj.save(update_fields=["commission_rate_applied"])


def unbackfill(apps, schema_editor):
    """Nothing to undo: the column goes with the migration."""


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_request_amount_edits_and_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='commission_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='نسبة العمولة المطبَّقة لكل 100 دولار'),
        ),
        migrations.RunPython(backfill_commission_rate, unbackfill),
    ]
