# Generated by Django 5.2.6 on 2026-08-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_request_commission_rate_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-submitted_at', '-id'], 'permissions': [('route_request', 'إسناد الطلب إلى تاجر'), ('approve_request', 'اعتماد الطلب'), ('credit_request', 'تسجيل الإيداع في B2CORE'), ('close_request', 'إغلاق الطلب'), ('confirm_request', 'تأكيد تنفيذ الطلب'), ('reject_request', 'رفض الطلب'), ('view_all_requests', 'عرض جميع الطلبات وليس المُسندة فقط'), ('return_request', 'إعادة الطلب إلى المالية'), ('cancel_request', 'إلغاء الطلب'), ('change_request_amount', 'تعديل مبلغ الطلب'), ('export_reports', 'تصدير التقارير إلى ملف')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
    ]
