# Generated by Django 5.2.6 on 2026-08-25 07:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_wallet(apps, schema_editor):
    """Point old requests at the wallet they were almost certainly shown.

    The link did not exist when these rows were written, only the snapshotted
    number. Matched back on all three things that make a wallet unique in
    practice — the number, the merchant the client chose, and the method — and
    only where exactly one wallet answers. An ambiguous match is left null on
    purpose: ``Wallet.was_used`` falls back to the same snapshot comparison, so
    a null here costs nothing, while a wrong link would make a used wallet look
    like a different used wallet.
    """
    Request = apps.get_model("transactions", "Request")
    Wallet = apps.get_model("merchants", "Wallet")

    rows = Request.objects.filter(wallet__isnull=True).exclude(
        wallet_number_snapshot=""
    ).values("pk", "wallet_number_snapshot", "payment_method_id", "merchant_selected_id")

    for row in rows.iterator():
        matches = list(
            Wallet.objects.filter(
                number=row["wallet_number_snapshot"],
                merchant_method__payment_method_id=row["payment_method_id"],
                merchant_method__merchant_id=row["merchant_selected_id"],
            )[:2]
        )
        if len(matches) == 1:
            Request.objects.filter(pk=row["pk"]).update(wallet=matches[0])


def forget_wallet(apps, schema_editor):
    """Nothing to undo: the column goes with the field."""


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_merchant_and_wallet_archive'),
        ('transactions', '0007_request_amount_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='merchants.wallet', verbose_name='المحفظة'),
        ),
        migrations.RunPython(backfill_wallet, forget_wallet),
    ]
